core/urls.py
import django.conf.urls
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gerenciar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gerenciar/urls.py
from django.contrib import admin
from django.urls import path
from .views import matriculaUpdateView, index, matriculaDetailView, matriculaCreateView,  matriculaListView
from .views import matriculaDeleteView, matriculaPDFDetailView, frequenciaCreateview, frequenciaListView, frequenciaUpdatesaida, frequenciaDeleteView
from .views import exercicioListView, exercicioCreateView, exercicioDeleteView
from .views import treinoDeleteView, treinoListView, treinoDetailView, treinoPDFDetailView,  treino, treinoUpdateView



urlpatterns = [
    path('', index.as_view(), name="index"),
    path('matricula', matriculaCreateView.as_view(), name="matricula"),
    path('alunos', matriculaListView.as_view(), name="listar_matricula"),
    path('matricula/atualizar/<int:pk>', matriculaUpdateView.as_view(), name="atualizar_matricula"),
    path('matricula/detalhar/<int:pk>', matriculaDetailView.as_view(), name="detalhar_matricula"),
    path('matricula/deletar/<int:pk>', matriculaDeleteView.as_view(), name="deletar_matricula"),
    path('matricula/pdf/<int:pk>', matriculaPDFDetailView.as_view(), name="pdf_matricula"),


    path('frequencia', frequenciaCreateview.as_view(), name="frequencia"),
    path('lista/frequencia', frequenciaListView.as_view(), name="listar_frequencia"),
    path('frequencia/atualizar/<int:pk>', frequenciaUpdatesaida.as_view(), name="saida"),
    path('frequencia/deletar/<int:pk>', frequenciaDeleteView.as_view(), name="deletar_frequencia"),


    path('exercicio', exercicioCreateView.as_view(), name="cadastrar_exercicio"),
    path('exercicios', exercicioListView.as_view(), name="listar_exercicio"),
    path('exercicio/<int:pk>', exercicioDeleteView.as_view(), name="deletar_exercicio"),


    path('treino', treino.as_view(), name="treino"),
    path('treinos', treinoListView.as_view(), name="listar_treino"),
    path('treino/atualizar/<int:pk>', treinoUpdateView.as_view(), name="atualizar_treino"),
    path('treino/detalhar/<int:pk>', treinoDetailView.as_view(), name="detalhar_treino"),
    path('treino/deletar/<int:pk>', treinoDeleteView.as_view(), name="deletar_treino"),
    path('treino/pdf/<int:pk>', treinoPDFDetailView.as_view(), name="pdf_treino"),
]

gerenciar/models.py
import uuid
from django.db import models
from django.utils import timezone
#from stdimage.models import StdImageField

def get_image_path(_instance, imagename):
    ext = imagename.split('-')[-1]
    imagename = f'{uuid.uuid4()}.{ext}'
    return imagename

# Create your models here.


class matricula(models.Model):
    PLANO_CHOICES = (
        ("1", "Musculação"),
        ("2", "Cross"),
        ("3", "Musculação + Cross")

    )
    SEXO_CHOICES = (
        ("M", "Masculino"),
        ("F", "Feminino"),
        ("O", "Outros"),
        ("NI", "Não Informado")

    )
    nome = models.CharField(max_length=40, blank=False, verbose_name="Nome do Cliente")  #unique = True - O valor é único e não pode ser repetido
    cpf = models.CharField(max_length=14, null=True, blank=True, unique=True, verbose_name="CPF")
    email = models.EmailField(max_length=40, blank=False, unique=True, verbose_name="Email")
    sexo = models.CharField(choices=SEXO_CHOICES, max_length=3, null=True, blank=False, verbose_name="Sexo")
    telefone = models.CharField(max_length=15, blank=False, null=True, verbose_name="Telefone")
    endereco = models.CharField(max_length=240, blank=False, null=False, verbose_name="Endereço")
    data_da_matricula = models.DateField(auto_now_add=True, verbose_name="Data da Matricula")
    data_de_vencimento = models.DateField(blank=False, null=False, verbose_name='Vencimento')
    foto_aluno= models.ImageField(blank=True, null=True, verbose_name="Foto do Aluno", upload_to='alunos')
    plano = models.CharField(max_length=2, null=False, blank=False, choices=PLANO_CHOICES, verbose_name="Plano")
    valor = models.CharField(max_length=6, null=False, blank=False, verbose_name="Subtotal")
    desconto = models.CharField(max_length=5, null=False, blank=True, verbose_name="Desconto")
    valor_total = models.CharField(max_length=6, null=False, blank=False, verbose_name="Valor da Mensalidade", editable=False)
    num_matricula = models.AutoField(primary_key=True, blank=False, null=False, unique=True, verbose_name="Número da Matricula")
    observacoes = models.TextField(max_length=512, blank=True, null=True, verbose_name="Obeservações")

    #class Meta:
        #verbose_name = 'Matricula'
        #verbose_name_plural = 'Matriculas'

    def __str__(self):
        return f' {self.nome}'

    def save(self, *args, **kwargs):
        self.valor_total = self.valor - self.desconto
        return super(matricula, self).save(*args, **kwargs)

#############################Avaliação#########################################

class avaliacao(models.Model):
    nome = models.ForeignKey('matricula', on_delete=models.DO_NOTHING, default=1, verbose_name="Aluno")
    idade = models.DecimalField(max_digits=2, decimal_places=0, null=False, blank=False, verbose_name="Idade")
    altura = models.DecimalField(max_digits=3, decimal_places=2, null=False, blank=False, verbose_name="altura")
    imc = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="IMC")
    cintura = models.DecimalField(max_digits=3, decimal_places=0, null=False, blank=False, verbose_name="Circunferência Cintura (cm)")
    quadril = models.DecimalField(max_digits=3, decimal_places=0, null=False, blank=False, verbose_name="Circunferência Quadril (cm)")
    rcq = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="RCQ")
    d3 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Subescapular")
    d1 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Tricipital")
    d4 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Peitoral")
    d5 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Axilar Média")
    d6 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Supra-Ilíaca")
    d7 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Cutânea Abdominal")
    d8 = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="Femural Médio")
    gordura = models.DecimalField(max_digits=4, decimal_places=2, null=False, blank=False, verbose_name="% de Gordura")

    def __str__(self):
        return f' {self.nome}'




class ficha_de_saude(models.Model):
    VERDADEIRO_CHOICES = (
        ("S", "Sim"),
        ("N", "Não"),
        ("NI", "Não Informado")
    )
    nome = models.ForeignKey('matricula', on_delete=models.DO_NOTHING, default=1, verbose_name="Aluno")
    #matricula =
    diabetes = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Diabetes")
    hipertensao = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Hipertensão")
    artrite = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Artrite")
    artrose = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Artrose")
    reumatismo = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Reumatismo")
    doencas_cardiacas = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Doenças Cardiacas")
    avc = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Já Sofreu AVC")
    fuma = models.CharField(max_length=2, choices=VERDADEIRO_CHOICES, blank=False, null=True, verbose_name="Tabagismo")
    BEBIDA_CHOICES = (
        ("S", "Sempre que Posso"),
        ("O", "Ocasionalmente"),
        ("R", "Raramente"),
        ("N", "Não Bebo")
    )
    bebe = models.CharField(max_length=1, choices=BEBIDA_CHOICES, blank=False, null=True, verbose_name="Bebe")
    #personal = models.ForeignKey('personal', on_delete=models.DO_NOTHING, default=1, verbose_name='Personal Responsável')

    def __str__(self):
        return f'{self.nome}'


class medicamento(models.Model):
    TRUE_CHOICES = (
        ("S", "Sim"),
        ("N", "Não")
    )
    nome = models.ForeignKey('matricula', on_delete=models.DO_NOTHING, default=1, verbose_name='Aluno')
    insulina=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Insulina")
    antidepressivos=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Antidepressivos")
    antihistaminicos=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Anti-Histaminicos (Alergia)")
    betabloqueadores=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Betabloqueadores (Hipertensão)")
    analgesicos=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Analgésicos")
    ansiolitico=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Ansiolítico (Ansiedade)")
    suplementos_vit=models.CharField(max_length=2, choices=TRUE_CHOICES, null=False, blank=False, verbose_name="Suplementos Vitamínicos")
    observacoes = models.TextField(max_length=140, null=True, blank=True, verbose_name="Observações")
    #personal = models.ForeignKey('personal', on_delete=models.DO_NOTHING, default=1, verbose_name='Personal Responsável')

    def __str__(self):
        return f'{self.nome}'

####Exercícios

class cadastrar_exercicio(models.Model):
    exercicio = models.CharField(max_length=32, null=False, blank=False,verbose_name='Exercicio')


    def __str__(self):
        return f'{self.exercicio}'



###Treino


class treinoA(models.Model):
    nome = models.ForeignKey('matricula', on_delete=models.DO_NOTHING, default=None, verbose_name="Aluno")
    aexc_1 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A1')
    rep1 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_2 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A2')
    rep2 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_3 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A3')
    rep3 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_4 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A4')
    rep4 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_5 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A5')
    rep5 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_6 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A6')
    rep6 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_7 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A7')
    rep7 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_8 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A8')
    rep8 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_9 = models.CharField(max_length=32, blank=False, null=False, verbose_name='A9')
    rep9 = models.CharField(max_length=6, blank=False, null=False, verbose_name='RP')
    aexc_10 = models.CharField(max_length=32, blank=True, null=False, verbose_name='A10')
    rep10 = models.CharField(max_length=6, blank=True, null=False, verbose_name='RP')
    aexc_11 = models.CharField(max_length=32, blank=True, null=False, verbose_name='A11')
    rep11 = models.CharField(max_length=6, blank=True, null=False, verbose_name='RP')
    aexc_12 = models.CharField(max_length=32, blank=True, null=False, verbose_name='A12')
    rep12 = models.CharField(max_length=6, blank=True, null=False, verbose_name='RP')

gerenciar/views.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DetailView, TemplateView, FormView, DeleteView, View
from django.shortcuts import render
from .models import matricula, treinoA, frequencia, ficha_de_saude, medicamento, cadastrar_exercicio
from .forms import matriculaForm, frequencia_saida, frequencia_entrada
from easy_pdf.views import PDFTemplateResponseMixin
from django.http import HttpResponseRedirect



# Create your views here.
#def index(request):
    #return render(request, 'index.html')

class index(TemplateView):
    template_name = 'index.html'

class indexadmin(TemplateView):
    template_name = 'adminlte/pages/index.html'


class matriculaCreateView(CreateView):
    model = matricula
    form_class = matriculaForm
    template_name = 'cadastrar/matricula.html'


    def get_success_url(self):
        messages.success(self.request, 'Aluno cadastrada com suceso!')
        return reverse_lazy("listar_matricula")


class matriculaListView(ListView):
    model = matricula
    template_name = 'listar/matricula.html'
    paginate_by = 50
    ordering = '-pk'


class matriculaUpdateView(UpdateView):
    model = matricula
    template_name = 'atualizar/matricula.html'

    fields = '__all__'

    def get_success_url(self):
        messages.success(self.request, 'Avaliação atualizada com sucesso!')
        return reverse_lazy('listar_matricula')

class matriculaDetailView(DetailView):
    model = matricula
    template_name = 'detalhar/matricula.html'

class matriculaPDFDetailView(PDFTemplateResponseMixin, DetailView):
    model = matricula
    template_name = 'detalhar/matriculapdf.html'





class matriculaDeleteView(DeleteView):
    model = matricula
    template_name = 'excluir/matricula.html'

    def get_success_url(self):
        messages.success(self.request, 'Aluno excluído com Sucesso!')




#################TREINO##########################

class treino(CreateView):
    model = treinoA
    template_name = 'cadastrar/treino.html'
    fields = '__all__'

    def get_success_url(self):
        messages.success(self.request, 'Treino cadastrado Sucesso!')
        return reverse_lazy("listar_treino")


class treinoListView(ListView):
    model = treinoA
    template_name = 'listar/treino.html'
    paginate_by = 100
    ordering = '-pk'


class treinoUpdateView(UpdateView):
    model = treinoA
    template_name = 'atualizar/treino.html'
    fields = '__all__'

    def get_success_url(self):
        messages.success(self.request, 'Treino atualizado Sucesso!')
        return reverse_lazy("listar_treino")


class treinoDeleteView(DeleteView):
    model = treinoA
    template_name = 'excluir/treino.html'

    def get_success_url(self):
        messages.success(self.request, 'Treino excluido Sucesso!')
        return reverse_lazy("listar_treino")



class treinoDetailView(DetailView):
    model = treinoA
    template_name = 'detalhar/treino.html'

class treinoPDFDetailView(PDFTemplateResponseMixin, DetailView):
    model = treinoA
    template_name = 'detalhar/treinopdf.html'



##########FREQUENCIA#################

class frequenciaCreateview(CreateView):
    model = frequencia
    form_class = frequencia_entrada
    template_name = 'cadastrar/frequencia.html'


    def get_success_url(self):
        messages.success(self.request, 'Entrada adicionada com Sucesso!')
        return reverse_lazy("listar_frequencia")

class frequenciaListView(ListView):
    model = frequencia
    template_name = 'listar/frequencia.html'
    paginate_by = 1000
    ordering = '-pk'

class frequenciaUpdatesaida(UpdateView):
    model = frequencia
    form_class = frequencia_saida
    template_name = 'atualizar/frequencia.html'

    def get_success_url(self):
        messages.success(self.request, 'Saída adicionada com Sucesso!')
        return reverse_lazy("listar_frequencia")

class frequenciaDeleteView(DeleteView):
    model = frequencia
    template_name = 'excluir/frequencia.html'

    def get_success_url(self):
        messages.success(self.request, 'Aluno excluído com Sucesso!')
        return reverse_lazy("listar_frequencia")


#######Exercicio###########



class exercicioCreateView(CreateView):
    model = cadastrar_exercicio
    template_name = 'cadastrar/exercicio.html'
    fields = '__all__'


    def get_success_url(self):
        messages.success(self.request, 'exercicio cadastrado com Sucesso!')
        return reverse_lazy("cadastrar_exercicio")

class exercicioListView(ListView):
    model = cadastrar_exercicio
    template_name = 'listar/exercicio.html'
    paginate_by = 100
    ordering = '-pk'

class exercicioDeleteView(DeleteView):
    model = cadastrar_exercicio
    template_name = 'excluir/exercicio.html'

    def get_success_url(self):
        messages.success(self.request, 'Aluno excluído com Sucesso!')
        return reverse_lazy("listar_exercicio")

gerenciar/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        {% block footer_right %}
        <b>Versão</b> {% block version %}2.3.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
        <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> 2021 Todos os direitos reservados.
    {% endblock %}
    {% endblock %}
</footer>

gerenciar/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-success navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Pagina Inicial</a>
        </li>
       <!-- <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Admin</a>
        </li> -->
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}

    {% block nav_custom_menu %}
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            {% block header_dropdowns %}
              <!-- Messages Dropdown Menu -->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-comments"></i>
                  <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Brad Diesel
                          <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Call me whenever you can...</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user4-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          John Pierce
                          <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">I got your message bro</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Nora Silvester
                          <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">The subject goes here</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
              </li>
                <!-- Notifications Dropdown Menu -->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-bell"></i>
                  <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <span class="dropdown-item dropdown-header">15 Notifications</span>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                  <i class="fas fa-expand-arrows-alt"></i>
                </a>
              </li>
            {% block user_info %}

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                  <img src="{%avatar_url 128 %}" class="user-image img-circle elevation-2" alt="User Image">
                  <span class="d-none d-md-inline">{% firstof request.user.get_short_name request.user.get_username %}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <!-- User image -->
                  <li class="user-header bg-primary">
                    <img src="{%avatar_url size=160 %}" class="img-circle elevation-2" alt="User Image">

                    <p>
                        {% firstof request.user.get_short_name request.user.get_username %} - {% firstof request.user.get_role %}
                      <small>Member since : {{ request.user.date_joined }}</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="row">
                      <div class="col-4 text-center">
                        <a href="#">Profile</a>
                      </div>
                      <div class="col-4 text-center">
                        <a href="#">Team</a>
                      </div>
                      <div class="col-4 text-center">
                        <a href="#">Friends</a>
                      </div>
                    </div>
                    <!-- /.row -->
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-default btn-flat">{% trans 'Change Password'%}</a>
                    <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat float-right">{% trans 'Sign Out'%}<a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>

    {% endblock nav_custom_menu %}

{% endblock %}
</nav>

gerenciar/templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.mask.min.js' %}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script>

                $(document).ready(function(){


                  $("#id_repetições").mask("0x00");
                  $("#id_cpf").mask("000.000.000-00");
                  $('#id_entrada').mask('00:00');
                  $('#id_saida').mask('00:00');
                  $('#id_data_de_vencimento').mask('00/00/0000');
                  var SPMaskBehavior = function (val) {
  return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
},
spOptions = {
  onKeyPress: function(val, e, field, options) {
      field.mask(SPMaskBehavior.apply({}, arguments), options);
    }
};

$('#id_telefone').mask(SPMaskBehavior, spOptions);

                });
        </script>



<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}
<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}